// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LigerShark.Farticus
{
    static class Vsix
    {
        public const string Id = "1324ce08-8b25-440c-1234-07e1fa0cce4a";
        public const string Name = "Farticus";
        public const string Description = @"The original Visual Studio fart app";
        public const string Language = "en-US";
        public const string Version = "1.8";
        public const string Author = "LigerShark";
        public const string Tags = "fart, sound";
    }
}
